global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'kafka'
    scrape_interval: 5s
    static_configs:
      - targets: ['kafka-1:8080','kafka-2:8080','kafka-3:8080']

  - job_name: 'docker'
    scrape_interval: 15s
    static_configs:
      - targets: ['container-exporter:9104']